pcpath: /root/p2m/data/fib_sphere_1000_30_empty.ply
initmeshpath: /root/p2m/data/fib_sphere_1000_30_empty_initmesh.obj
savepath: /root/p2m/checkpoints/fib_sphere_1000_30_empty/
manifoldpath: /root/code/Manifold/build

bfs_depth: 0
# faces_to_part: [8000, 16000, 20000]


## model parameters
in_channel: 6
convs: [16, 32, 64, 64, 128]
pools: [0.0, 0.0, 0.0, 0.0]
res_blocks: 3
transfer: True
leaky: 0.01 ## slope for leaky relu
init_weights: 0.002

learning_rate: 0.00011
iters: 5000

thres: 0.99

samples: 160000
start_samples: 100000
upsample: 500
slope: 0.8

beamgap-iter: 0
beamgap-mod: 2
norm_weight: 0.1 


export_period: 100
max_face: 30000
manifold_res: 100000

disable_net: False