pcpath: /root/p2m/data/guitar_noise0.ply
initmeshpath: /root/p2m/data/guitar_noise0_initmesh.obj
savepath: /root/p2m/checkpoints/guitar_noise0/
manifoldpath: /root/code/Manifold/build
# pcpath: /root/p2m/data/guitar.ply
# initmeshpath: /root/p2m/data/guitar_initmesh.obj
# savepath: /root/p2m/checkpoints/guitar/
# manifoldpath: /root/code/Manifold/build
bfs_depth: 0
# faces_to_part: [8000, 16000, 20000]


## model parameters
in_channel: 6
convs: [16, 32, 64, 64, 128]
pools: [0.0, 0.0, 0.0, 0.0]
res_blocks: 3
transfer: True
leaky: 0.01 ## slope for leaky relu
init_weights: 0.002
global_opt : True

learning_rate: 0.00011
iters: 10005

thres: 0.99

samples: 25000
start_samples: 15000
upsample: 1000
slope: 0.8

beamgap-iter: 0
beamgap-mod: 2
norm_weight: 0.1 


export_period: 1000
max_face: 23716
manifold_res: 100000

disable_net: False